nome = input('Digite o seu nome completo: ')
maiuscula = nome.upper()
minuscula = nome.lower()
total = len(nome) - nome.count(' ')
first = nome.split(" ")
print(f'seu nome em maiúsculas é: {maiuscula}')
print(f'seu nome em minúsculas é: {minuscula}')
print(f'seu nome tem ao todo {total} letras')
print(f'seu primeiro nome é {first[0]} e ele tem {len(first[0])} letras')